# -*- coding: utf-8 -*-
# Données 2026 — bilan provisoire, repris des extraits BNP Paribas Fortis
# BE23 0019 5419 0591 — BV MT COSMETICS BELGIUM
#
# Même convention qu'en 2025 : les charges de décembre 2025 débitées début
# janvier 2026 (précompte salarial 2.250,00 et SD Worx 331,85) sont comptées
# dans le bilan 2025 et donc EXCLUES ici. L'extrait 2026-001 ne se rapproche
# pas du solde pour cette raison : écart voulu de 2.581,85.

MOIS = []

MOIS.append(("Janvier", {
 "solde_debut": 8522.89, "solde_fin": 1378.82, "extrait": "2026 - 001",
 "entrees": [],   # aucun encaissement du mois
 "depenses": [
    ("Carburant",                                         69.70, "Shell Kraainem"),
    ("Achat matériel sportif - DECATHLON",                240.00, "Decathlon Evere"),
    ("Achat matériel sportif - DECATHLON",                108.50, "Decathlon Evere"),
    ("Parking",                                           4.80, "Woluwe-Saint-Lambert"),
    ("Crédit voiture",                                    724.12, ""),
    ("Entretien voiture - Auto 5 Kraainem",               1094.40, ""),
    ("Entretien voiture - Auto 5 Kraainem",               70.00, ""),
    ("Carburant",                                         44.88, "Lukoil Wezembeek"),
    ("Carburant",                                         65.20, "Total Saverne (France)"),
    ("Frais bancaires trimestriels",                      11.25, ""),
    ("Carburant",                                         57.46, "BP Vaduz (Liechtenstein) — 51,90 CHF"),
    ("Parking",                                           20.30, "Parkhaus Bahnhofplatz, Coire (Suisse) — 18,00 CHF"),
    ("Carburant",                                         73.48, "Esso Brumath (France)"),
    ("Parking",                                           1.85, "Q-Park Woluwe Esplanade"),
    ("Carburant",                                         74.63, "Q8 Easy Zaventem"),
    ("Assurance voiture",                                 458.66, "Domiciliation AG Insurance"),
    ("Proximus",                                          184.72, ""),
    ("Parking",                                           11.00, "Parking Grand-Place, Bruxelles"),
    ("Carburant",                                         64.57, "Shell Kraainem"),
    ("Frais comptable BDH",                               1179.75, "Facture 20250542 — facture 2025 payée en 2026"),
    ("Parking",                                           1.60, "Woluwe-Saint-Lambert"),
    ("Parking",                                           1.35, "Schaerbeek"),
 ],
}))

MOIS.append(("Février", {
 "solde_debut": 1378.82, "solde_fin": 4396.43, "extrait": "2026 - 02",
 "entrees": [
    ('LAM2601', 4057.5, ''),
    ('Approvisionnement compte - Thibault Duchène', 1000.0, 'Apport du gérant, pas un produit — à traiter en compte courant'),
    ('Alimentation du compte - Thibault Duchène', 1000.0, 'Apport du gérant, pas un produit — à traiter en compte courant'),
    ('LAM2602', 5790.15, ''),
    ('Remboursement contrats Babolat - RTC Lambermont', 440.0, ''),
 ],
 "depenses": [
    ('Parking', 3.7, 'Administration communale, Bruxelles'),
    ('Carburant', 63.37, ''),
    ('Précompte salarial janvier 2026 Thibault Duchène', 2250.0, ''),
    ('SD Worx', 332.49, ''),
    ('Parking', 3.8, ''),
    ('Crédit voiture', 724.12, ''),
    ('Farys (eau)', 306.0, ''),
    ('Abonnement club David Lloyd', 1027.75, 'Sterrebeek — usage professionnel à confirmer'),
    ('Parking', 10.2, ''),
    ('Abonnement club David Lloyd', 1061.0, 'Sterrebeek — usage professionnel à confirmer'),
    ('Electrabel', 263.44, ''),
    ('Réception marchandise - FEDEX', 11.84, ''),
    ('Parking', 3.8, ''),
    ('Carburant', 64.24, ''),
    ('Parking', 7.6, ''),
    ('Parking', 1.9, ''),
    ('Parking', 3.4, ''),
    ('Carburant', 63.63, ''),
    ('Péage autoroute France', 42.0, ''),
    ('Consommation - SV Victoria', 16.5, 'Rotterdam (Pays-Bas)'),
    ('Consommation - SV Victoria', 4.45, 'Rotterdam (Pays-Bas)'),
    ('Parking', 8.1, ''),
    ('Achat vêtements sport - NIKE', 230.48, ''),
    ('Achat vêtements sport - Sportsdirect', 112.0, ''),
    ('Parking', 3.4, ''),
    ('Carburant', 62.54, ''),
    ('Parking', 3.8, ''),
    ('Précompte salarial fevrier 2026 Thibault Duchène', 2250.0, ''),
    ('SD Worx', 332.49, ''),
    ('Parking', 2.0, ''),
 ],
}))

MOIS.append(("Mars", {
 "solde_debut": 4396.43, "solde_fin": 1885.38, "extrait": "2026 - 03",
 "entrees": [
    ("Dépôt d'espèces", 2600.0, 'Versement au distributeur, communication « PAIEMENTS » — origine des fonds à documenter'),
    ('Remboursement hôtel Imola - Thibault Duchène', 364.5, ''),
    ('Remboursement billet de train Bologne - Thibault Duchène', 197.3, ''),
    ('LAM2603', 4110.0, ''),
 ],
 "depenses": [
    ('Achat vêtements sport - NIKE', 130.46, ''),
    ('Parking', 4.5, ''),
    ('Parking', 1.7, ''),
    ('Carburant', 64.62, ''),
    ('Crédit voiture', 724.12, ''),
    ('Parking', 5.7, ''),
    ('Partena', 1747.34, ''),
    ('Partena', 935.96, ''),
    ('Proximus', 293.82, ''),
    ('Electrabel', 263.44, ''),
    ('Parking', 3.4, ''),
    ('Parking', 1.7, ''),
    ('Remboursement alimentation du compte - Thibault Duchène', 750.0, 'Restitution des apports de février 2026'),
    ('Carburant', 76.45, ''),
    ('Paiement carte de crédit', 1104.46, ''),
    ('Parking', 3.4, ''),
    ('Carburant', 65.54, ''),
    ('Parking', 2.3, ''),
    ('Carburant', 63.82, ''),
    ('Parking', 9.0, 'Düsseldorf (Allemagne)'),
    ('Parking', 10.0, 'Düsseldorf (Allemagne)'),
    ('Carburant', 84.56, ''),
    ('Parking - Chirec', 7.8, 'Hôpital, Bruxelles — à confirmer'),
    ('Parking', 2.1, ''),
    ('Précompte salarial mars 2026 Thibault Duchène', 2250.0, ''),
    ('Achat - Berca', 38.97, 'Ardooie — à identifier'),
    ('Parking', 6.0, 'Italie'),
    ('Parking', 2.45, 'Italie'),
    ('Parking', 9.25, 'Italie'),
    ('Remboursement alimentation du compte - Thibault Duchène', 750.0, 'Restitution des apports de février 2026'),
    ('SD Worx', 332.49, ''),
    ('Parking', 36.5, 'Italie'),
    ('Parking', 1.0, 'Italie'),
 ],
}))

MOIS.append(("Avril", {
 "solde_debut": 1885.38, "solde_fin": 2570.25, "extrait": "2026 - 04",
 "entrees": [
    ('LAM2604', 7000.0, ''),
    ("Remboursement d'impôt - SPF Finances", 2349.66, 'Rôle 0867847943'),
 ],
 "depenses": [
    ('Carburant', 64.48, 'ENI (Italie)'),
    ('Parking', 10.0, 'Italie'),
    ('Parking', 5.5, 'Italie'),
    ('Parking', 5.0, 'Italie'),
    ('Parking', 2.0, 'Italie'),
    ('Parking', 6.0, 'Italie'),
    ('Parking', 2.0, 'Italie'),
    ('Carburant', 76.5, 'ENI (Italie)'),
    ('Parking', 39.5, 'Italie'),
    ('Crédit voiture', 724.12, ''),
    ('Proximus', 264.52, ''),
    ('Lavage voiture', 34.0, 'Wash Time Tervuren'),
    ('Transport - STIB', 2.4, ''),
    ('Versement impôts anticipé', 5000.0, 'Comm. 073/4616/33527'),
    ('Frais comptable BDH', 254.1, ''),
    ('Parking', 3.8, 'Italie'),
    ('Farys (eau)', 306.0, ''),
    ('Repas Lunch Garden', 30.48, ''),
    ('Frais bancaires trimestriels', 11.25, ''),
    ('Collation', 16.9, ''),
    ('Parking', 1.7, ''),
    ('Paiement carte de crédit', 275.86, ''),
    ('Carburant', 80.9, ''),
    ('Parking', 3.4, ''),
    ('Parking', 7.2, ''),
    ('Redevance de stationnement - OPC', 5.5, 'à confirmer (redevance ou amende)'),
    ('Carburant', 77.88, ''),
    ('Parking', 1.7, ''),
    ('Repas Lunch Garden', 16.54, ''),
    ('Achat - Orgefi SPRL', 9.5, 'Nivelles — à identifier'),
    ('Carburant', 4.35, 'Total Schaerbeek'),
    ('Achat - Orgefi SPRL', 3.6, 'Nivelles — à identifier'),
    ('Assurance voiture', 458.66, ''),
    ('Electrabel', 270.94, ''),
    ('Electrabel', 263.44, ''),
    ('Proximus', 226.02, ''),
    ('Réception marchandise - UPS', 8.03, ''),
    ('Repas Lunch Garden', 51.02, ''),
    ('Redevance de stationnement - OPC', 40.0, 'à confirmer (redevance ou amende)'),
 ],
}))

MOIS.append(("Mai", {
 "solde_debut": 2570.25, "solde_fin": 1436.97, "extrait": "2026 - 05",
 "entrees": [
    ('LAM2605', 4619.2, ''),
 ],
 "depenses": [
    ('Carburant', 89.01, ''),
    ('Parking', 1.7, ''),
    ('Précompte salarial avril 2026 Thibault Duchène', 2250.0, ''),
    ('Partena', 1747.34, ''),
    ('Crédit voiture', 724.12, ''),
    ('Remboursement alimentation du compte - Thibault Duchène', 500.0, 'Restitution des apports de février 2026'),
    ('Collation', 8.0, ''),
    ('Collation', 3.0, ''),
    ('Carburant', 85.45, 'Total Schaerbeek'),
    ('Parking', 11.7, ''),
    ('Collation', 8.0, ''),
    ('Paiement carte de crédit', 40.6, ''),
    ('Parking', 0.5, ''),
    ('Carburant', 72.66, ''),
    ('Carburant', 6.55, ''),
    ('Parking', 4.2, ''),
    ('Abonnement salle FitRaw', 59.04, 'Sterrebeek — usage professionnel à confirmer'),
    ('Lavage voiture', 32.0, 'Wash Time Tervuren'),
    ('Parking', 1.7, ''),
    ('Carburant', 79.51, ''),
    ('Parking', 15.6, 'Schiphol (Pays-Bas)'),
    ('Parking', 5.0, ''),
    ('Parking', 6.8, ''),
 ],
}))

MOIS.append(("Juin", {
 "solde_debut": 1436.97, "solde_fin": 687.43, "extrait": "2026 - 06",
 "entrees": [
    ('LAM2606', 4803.5, ''),
    ("Remboursement billet d'avion - Thibault Duchène", 1815.16, ''),
 ],
 "depenses": [
    ('Carburant', 75.41, ''),
    ('Abonnement club David Lloyd', 493.0, 'Sterrebeek — usage professionnel à confirmer'),
    ('Crédit voiture', 724.12, ''),
    ('Carburant', 83.72, ''),
    ('Parking', 43.75, ''),
    ('Précompte salarial mai 2026 Thibault Duchène', 2250.0, ''),
    ('SD Worx', 332.84, ''),
    ('Proximus', 203.91, ''),
    ('Carburant', 80.15, ''),
    ('Parking', 1.9, ''),
    ('Lavage voiture', 17.0, 'Wash Time Tervuren'),
    ('Paiement carte de crédit', 1815.16, ''),
    ('Parking', 6.3, ''),
    ('Parking', 3.8, ''),
    ('Electrabel', 297.28, ''),
    ('Electrabel', 270.94, ''),
    ('Proximus', 239.76, ''),
    ('Carburant', 83.5, ''),
    ('Achat matériel sportif - DECATHLON', 82.5, ''),
    ('SD Worx', 32.84, ''),
    ('Parking', 8.43, ''),
    ('Parking', 35.0, ''),
    ('Divers - sanitaires autoroute', 0.8, 'Aire de Rotselaar'),
    ('Divers - sanitaires autoroute', 0.8, 'Aire de Rotselaar'),
    ('Carburant', 77.3, ''),
    ('Parking', 4.0, ''),
    ('Parking', 4.0, ''),
    ('Hôtel Ibis Nieuwpoort', 15.0, 'à confirmer (nuitée ou consommation)'),
    ('Parking', 8.0, ''),
    ('Carburant', 76.99, ''),
 ],
}))

MOIS.append(("Juillet", {
 "solde_debut": 687.43, "solde_fin": 4843.02, "extrait": "2026 - 07",
 "entrees": [
    ('LAM2607', 4156.08, ''),
    ('Remboursement SD Worx', 32.84, 'Cotisation payée deux fois'),
    ('LAM2608', 6448.4, ''),
    ('Remboursement Airbnb - Thibault Duchène', 2431.44, ''),
 ],
 "depenses": [
    ('Abonnement club David Lloyd', 493.0, 'Sterrebeek — usage professionnel à confirmer'),
    ('Précompte salarial juin 2026 Thibault Duchène', 2250.0, ''),
    ('SD Worx', 332.84, ''),
    ('SD Worx', 332.84, ''),
    ('Crédit voiture', 724.12, ''),
    ('Frais bancaires trimestriels', 11.25, ''),
    ('Carburant', 79.41, ''),
    ('Parking', 1.9, ''),
    ('Parking', 1.9, ''),
    ('Collation', 3.0, ''),
    ('Parking', 5.5, ''),
    ('Péage autoroute France', 69.3, ''),
    ('Carburant', 79.42, ''),
    ('Collation', 2.7, ''),
    ('Parking', 2.8, ''),
    ('Lavage voiture', 32.0, 'Wash Time Tervuren'),
    ('Achat matériel sportif - DECATHLON', 9.0, ''),
    ('Parking', 3.6, ''),
    ('Proximus', 180.92, ''),
    ('Carburant', 76.89, ''),
    ('Abonnement salle FitRaw', 22.86, 'Sterrebeek — usage professionnel à confirmer'),
    ('Précompte salarial juillet 2026 Thibault Duchène', 2250.0, ''),
    ('Assurance voiture - Yuzzu', 1190.65, ''),
    ('Entretien voiture - Monsieur Pneus', 423.98, ''),
    ('SD Worx', 333.29, ''),
 ],
}))

MOIS.append(("Août", {
 "solde_debut": 4843.02, "solde_fin": 5656.34, "extrait": "2026 - 08",
 "entrees": [
    ('LAM2609', 5341.8, ''),
    ('LAM2610', 5000.0, ''),
 ],
 "depenses": [
    ('Divers - Mister Minit', 19.9, ''),
    ('Achat matériel sportif - Bellissimo Sport', 12.0, ''),
    ('Parking', 1.7, ''),
    ('Farys (eau)', 306.0, ''),
    ('Electrabel', 141.56, ''),
    ('Crédit voiture', 724.12, ''),
    ('Abonnement club David Lloyd', 493.0, 'Sterrebeek — usage professionnel à confirmer'),
    ('Carburant', 98.54, ''),
    ('Carburant', 84.61, ''),
    ('Parking', 5.4, "Côte d'Azur (France)"),
    ('Parking', 7.5, "Côte d'Azur (France)"),
    ('Parking', 7.5, "Côte d'Azur (France)"),
    ('Parking', 9.5, "Côte d'Azur (France)"),
    ('Parking', 8.5, "Côte d'Azur (France)"),
    ('Parking', 9.0, ''),
    ('Achat - Castillon Fréjus', 80.0, 'France — à identifier'),
    ('Parking', 19.0, "Côte d'Azur (France)"),
    ('Parking', 10.6, "Côte d'Azur (France)"),
    ('Parking', 6.4, "Côte d'Azur (France)"),
    ('Parking', 4.2, "Côte d'Azur (France)"),
    ('Paiement carte de crédit', 2431.44, ''),
    ('Carburant', 75.33, 'E.Leclerc Mornas (France) — à confirmer'),
    ('Carburant', 83.85, ''),
    ('Carburant', 77.98, ''),
    ('Parking', 5.4, ''),
    ('Parking', 5.4, ''),
    ('Parking', 5.4, ''),
    ('Précompte salarial aout 2026 Thibault Duchène', 2250.0, ''),
    ('Partena', 1747.34, ''),
    ('SD Worx', 333.29, ''),
    ('Electrabel', 294.73, ''),
    ('Vlaamse Belastingsdienst - taxe de circulation', 167.59, ''),
    ('Parking', 1.7, ''),
 ],
}))
