# -*- coding: utf-8 -*-
# Données 2025 — reprises des extraits de compte BNP Paribas Fortis
# BE23 0019 5419 0591 — BV MT COSMETICS BELGIUM
#
# Convention retenue : les opérations débitées/créditées début janvier 2025 mais
# se rapportant à décembre 2024 (et déjà encodées dans le bilan 2024) sont
# EXCLUES de 2025. Le total du mois ne correspond donc volontairement pas à la
# variation de solde de l'extrait bancaire.

MOIS = []

MOIS.append(("Janvier", {
 "solde_debut": 1378.02, "solde_fin": 3407.94, "extrait": "2025 - 001",
 # Exclus car déjà dans le bilan 2024 (décembre) :
 #   entrée  LAM2415 4.743,17
 #   dépenses Repas Topogigio 26,00 / Précompte salarial déc. 2024 2.250,00 /
 #            SD Worx 330,88 / Electrabel 256,99 / Telenet 149,10 / Proximus 82,99
 "entrees": [
    ("LAM2501", 5328.20, ""),
    ("LAM2502", 7000.00, ""),
 ],
 "depenses": [
    ("Collation - Plouf et Baballe",                      8.40, ""),
    ("Carburant",                                         22.90, "Q8 Easy Zaventem"),
    ("Réception marchandise - FEDEX",                     5.69, ""),
    ("Parking",                                           1.35, ""),
    ("Carburant",                                         62.79, "Cora Woluwe — à confirmer (carburant ou achats ?)"),
    ("Crédit voiture",                                    724.12, ""),
    ("Frais bancaires trimestriels",                      11.25, ""),
    ("Assurance voiture",                                 431.25, "Paiement par domiciliation (AG Insurance)"),
    ("Repas Topogigio",                                   22.00, ""),
    ("Carburant",                                         66.72, "Q8 Easy Zaventem"),
    ("Parking",                                           22.50, "Parking Centraal Anvers"),
    ("Parking",                                           1.80, "Commune Saint-Josse"),
    ("Electrabel",                                        256.99, ""),
    ("Telenet",                                           159.10, ""),
    ("Parking",                                           1.60, "Woluwe-Saint-Lambert"),
    ("Carburant",                                         71.13, "Cora Woluwe — à confirmer (carburant ou achats ?)"),
    ("Péage autoroute France",                            27.90, "Domiciliation Autoroutes du Sud de la France"),
    ("Parking",                                           7.20, "Parking Rogier"),
    ("Parking",                                           2.68, ""),
    ("Billets d'avion Pérou - Translatina Travel",        1100.00, "Facture de l'agence à joindre"),
    ("Précompte salarial janvier 2025 Thibault Duchène",  2250.00, ""),
    ("Billets d'avion Pérou - Translatina Travel",        42.00, "Complément — facture à joindre"),
    ("Carburant",                                         69.44, "Lukoil Wezembeek"),
    ("Impôt des sociétés",                                4517.28, "Communication 202/9987/63859"),
    ("Frais comptable BDH",                               1125.30, "Facture 20240512"),
    ("SD Worx",                                           331.52, ""),
    ("Frais comptable BDH",                               290.40, "Facture 20240616"),
    ("Frais comptable BDH",                               242.00, "Facture 20240705"),
    ("Proximus",                                          70.18, ""),
 ],
}))

MOIS.append(("Février", {
 "solde_debut": 3407.94, "solde_fin": 2468.17, "extrait": "2025 - 002",
 "entrees": [
    ("LAM2503", 5145.00, ""),
    ("Remboursement Electrabel", 256.99, "Remboursement du double paiement de la facture 468/9192/57548"),
 ],
 "depenses": [
    ("Achat vêtements sport - PVH Maasmechelen",          210.49, ""),
    ("Achat vêtements sport - NIKE Maasmechelen",         141.47, ""),
    ("Parking",                                           2.10, "Indigo Park Docks"),
    ("Electrabel",                                        256.99, "Facture 468/9192/57548 payée 2× (16-01 et 04-02) — remboursée le 10-02"),
    ("Telenet",                                           149.10, ""),
    ("Carburant",                                         65.00, "Dats 24 Nossegem"),
    ("Crédit voiture",                                    724.12, ""),
    ("Parking",                                           1.80, "Schaerbeek"),
    ("Parking",                                           6.20, "Administration communale Bruxelles"),
    ("Parking",                                           2.50, "Parking Ixelles - Gand"),
    ("Parking",                                           17.10, "Q-Park Heilig Hart Louvain"),
    ("Carburant",                                         69.47, "Q8 Easy Zaventem"),
    ("Transport - STIB",                                  4.60, ""),
    ("Transport - De Lijn",                               2.50, ""),
    ("Parking",                                           2.50, "Parkeren Louvain"),
    ("Parking",                                           1.80, "Commune Saint-Josse"),
    ("Partena",                                           1441.87, ""),
    ("Farys (eau)",                                       290.00, ""),
    ("Parking",                                           6.50, "Parking Ixelles - Gand"),
    ("Carburant",                                         68.61, "Q8 Easy Zaventem"),
    ("Repas Lunch Garden",                                39.47, "LG Auderghem"),
    ("Achat matériel sportif - DECATHLON",                140.00, "Decathlon Evere"),
    ("Précompte salarial février 2025 Thibault Duchène",  2250.00, ""),
    ("SD Worx",                                           331.52, ""),
    ("Carburant",                                         66.07, "Q8 Easy Zaventem"),
    ("Proximus",                                          49.98, ""),
 ],
}))

MOIS.append(("Mars", {
 "solde_debut": 2468.17, "solde_fin": 3606.60, "extrait": "2025 - 003",
 "entrees": [
    ("LAM2504", 5000.00, ""),
    ("LAM2505", 4888.80, ""),
 ],
 "depenses": [
    ("Achat - NEW BS SPRL",                               290.50, "Bruxelles — commerçant à identifier"),
    ("Crédit voiture",                                    724.12, ""),
    ("Repas Topogigio",                                   75.50, ""),
    ("Parking",                                           6.30, "Brucity - Ville de Bruxelles"),
    ("Carburant",                                         67.55, "Q8 Limal"),
    ("Paiement carte VISA",                               7.30, "Décompte n° 060"),
    ("Electrabel",                                        256.99, "Facture 470/3433/24753"),
    ("Electrabel",                                        256.99, "Facture 440/7222/59244"),
    ("Telenet",                                           149.40, ""),
    ("Redevance de stationnement - Ville de Louvain",     58.00, "Comm. 194/3769/90294 — à confirmer (redevance ou amende)"),
    ("Redevance de stationnement - Woluwe-Saint-Lambert", 45.00, "Comm. 602/2505/46621 — à confirmer (redevance ou amende)"),
    ("Parking",                                           1.85, "Q-Park Woluwe Esplanade"),
    ("Parking",                                           6.00, "T and T Parking Bruxelles"),
    ("Carburant",                                         60.74, "Q8 Easy Zaventem"),
    ("Parking",                                           2.67, "Commune Saint-Josse"),
    ("Carburant",                                         50.20, "Station 15 Zemst"),
    ("Partena",                                           3014.00, ""),
    ("Entretien voiture - Monsieur Pneus",                919.17, ""),
    ("Carburant",                                         70.68, "Shell Kraainem"),
    ("Carburant",                                         16.00, "Station 15 Zemst"),
    ("Parking",                                           16.20, "Parking Rogier"),
    ("Parking",                                           3.20, "Woluwe-Saint-Lambert"),
    ("Précompte salarial mars 2025 Thibault Duchène",     2250.00, ""),
    ("SD Worx",                                           331.52, ""),
    ("Carburant",                                         70.49, "Q8 Easy Zaventem"),
 ],
}))

MOIS.append(("Avril", {
 "solde_debut": 3606.60, "solde_fin": 2248.45, "extrait": "2025 - 004",
 # Extrait arrêté au 26-04 : les opérations de fin de mois (précompte, SD Worx,
 # facture LAM) figureront sur l'extrait de mai.
 "entrees": [
    ("Remboursement billet d'avion Lima-Bruxelles", 1683.78, "Versement de Thibault Duchène - C. Garces Trujillo"),
 ],
 "depenses": [
    ("Repas Exki",                                        30.30, "Exki Woluwe"),
    ("Parking",                                           1.60, "Woluwe-Saint-Lambert"),
    ("Parking",                                           18.40, "Delft (Pays-Bas)"),
    ("Parking",                                           10.40, "Markthof La Haye (Pays-Bas) — à confirmer"),
    ("Crédit voiture",                                    724.12, ""),
    ("Parking",                                           23.00, "Stadparkeerplan Leyde (Pays-Bas)"),
    ("Frais bancaires trimestriels",                      11.25, ""),
    ("Carburant",                                         87.00, "Total Leyde (Pays-Bas)"),
    ("Parking",                                           10.46, "Commune d'Utrecht (Pays-Bas)"),
    ("Parking",                                           9.00, "Parking De Vooruitgang, Volendam (Pays-Bas)"),
    ("Achat - NZA Utrecht BV",                            289.97, "Amsterdam (Pays-Bas) — commerçant à identifier"),
    ("Proximus",                                          141.50, ""),
    ("Parking",                                           32.76, "Commune d'Utrecht (Pays-Bas)"),
    ("Telenet",                                           149.10, ""),
    ("Parking",                                           8.00, "Q-Park Sint Jorisplein, Amersfoort (Pays-Bas)"),
    ("Paiement carte VISA",                               433.78, "Décompte n° 091"),
    ("Assurance voiture",                                 431.25, "Paiement par domiciliation (AG Insurance)"),
    ("Carburant",                                         72.18, "Q8 Easy Zaventem"),
    ("Parking",                                           6.00, "T and T Parking Bruxelles"),
    ("Parking",                                           14.00, "Parking Casino Middelkerke"),
    ("Divers - sanitaires autoroute",                     1.00, "2theloo, aire E40 Jabbeke"),
    ("Divers - sanitaires autoroute",                     1.00, "2theloo, aire E40 Jabbeke"),
    ("Carburant",                                         64.07, "Q8 Easy Zaventem"),
    ("Collation",                                         0.80, "AC Restaurants Wanlin"),
    ("Electrabel",                                        256.99, "Facture 439/4769/34444"),
    ("Carburant",                                         60.37, "Lukoil Wezembeek"),
    ("Repas Topogigio",                                   26.00, ""),
    ("Achat matériel sportif - DECATHLON",                84.20, "Decathlon Evere"),
    ("Achat Delhaize",                                    43.43, "Delhaize Sterrebeek - 1er paiement avec la nouvelle carte 5255"),
 ],
}))

MOIS.append(("Mai", {
 "solde_debut": 2248.45, "solde_fin": 5358.10, "extrait": "2025 - 005",
 # Extrait du 26-04 au 29-05 : le précompte et SD Worx de mai basculent sur juin.
 "entrees": [
    ("LAM2506", 4554.60, ""),
    ("LAM2507", 5077.11, ""),
 ],
 "depenses": [
    ("Crédit voiture",                                    724.12, ""),
    ("Précompte salarial avril 2025 Thibault Duchène",    2250.00, ""),
    ("SD Worx",                                           331.99, ""),
    ("Farys (eau)",                                       290.00, ""),
    ("Proximus",                                          71.54, ""),
    ("Carburant",                                         59.49, "Cora Woluwe — à confirmer (carburant ou achats ?)"),
    ("Parking",                                           1.60, "Woluwe-Saint-Lambert"),
    ("Paiement carte VISA",                               2116.19, "Décompte n° 121"),
    ("Achat matériel sportif - DECATHLON",                50.00, "Decathlon Evere"),
    ("Telenet",                                           149.10, ""),
    ("Carburant",                                         66.09, "Lukoil Tervuren"),
    ("Divers - sanitaires autoroute",                     1.00, "Tank und Rastanlage, Frechen (Allemagne)"),
    ("Divers - sanitaires autoroute",                     1.00, "Tank und Rastanlage, Frechen (Allemagne)"),
    ("Parking",                                           16.50, "Bonner City Parkraum, Bonn (Allemagne)"),
    ("Carburant",                                         58.83, "Shell Kraainem"),
    ("Parking",                                           1.85, "Q-Park Woluwe Esplanade"),
    ("Parking",                                           1.85, "Q-Park Woluwe Esplanade"),
    ("Electrabel",                                        256.99, "Facture 493/0415/84633"),
    ("Carburant",                                         72.42, "Q8 Tervuren"),
    ("Parking",                                           1.50, "Ville de Dinant"),
 ],
}))

MOIS.append(("Juin", {
 "solde_debut": 5358.10, "solde_fin": 4930.12, "extrait": "2025 - 006",
 "entrees": [
    ("LAM2508", 4460.00, ""),
    ("Approvisionnement compte - Thibault Duchène", 1500.00, "Apport du gérant, pas un produit — à traiter en compte courant"),
 ],
 "depenses": [
    ("Achat matériel sportif - DECATHLON",                200.00, "Decathlon Evere"),
    ("Précompte salarial mai 2025 Thibault Duchène",      2250.00, ""),
    ("Partena",                                           1441.87, ""),
    ("SD Worx",                                           331.99, ""),
    ("Carburant",                                         55.61, "Q8 Easy Zaventem"),
    ("Parking",                                           3.70, "Q-Park Woluwe Esplanade"),
    ("Crédit voiture",                                    724.12, ""),
    ("Parking",                                           15.80, "RG Public, Paris (France) — à confirmer"),
    ("Carburant",                                         75.87, "Station Avia, Havrincourt (France)"),
    ("Parking",                                           31.05, "Indigo, Paris (France)"),
    ("Parking",                                           12.00, "Brussels Expo — à confirmer (parking ou entrée)"),
    ("Parking",                                           9.20, "Parking Ladeuze, Louvain"),
    ("Parking",                                           4.00, "Province du Brabant flamand, Kessel-Lo"),
    ("Paiement carte VISA",                               543.41, "Décompte n° 152"),
    ("Telenet",                                           155.52, ""),
    ("Proximus",                                          64.94, ""),
    ("Carburant",                                         68.06, "Q8 Easy Zaventem"),
    ("Parking",                                           9.00, "Parking Grand-Place, Bruxelles"),
    ("Parking",                                           3.60, "Parkeren Sint-Gillis, Gand"),
    ("Parking",                                           5.00, "Parking FP1, Zaventem"),
    ("Carburant",                                         64.97, "Lukoil Tournai"),
    ("Electrabel",                                        256.99, "Facture 450/5974/91764"),
    ("Parking",                                           1.85, "Q-Park Woluwe Esplanade"),
    ("Carburant",                                         54.33, "Q8 Easy Zaventem"),
    ("Parking",                                           3.50, "Parking Sint-Pieters, Gand"),
    ("Parking",                                           1.60, "Woluwe-Saint-Lambert"),
 ],
}))

MOIS.append(("Juillet", {
 "solde_debut": 4930.12, "solde_fin": 8568.89, "extrait": "2025 - 007",
 "entrees": [
    ("Remboursement paiement à Sandaya", 1775.40, "Versement de Thibault Duchène — dépense privée payée par la société ?"),
    ("Prestations juillet 2025 - RTC Lambermont", 7130.00, "Communication sans numéro de facture LAM"),
 ],
 "depenses": [
    ("Précompte salarial juin 2025 Thibault Duchène",     2250.00, ""),
    ("SD Worx",                                           331.99, ""),
    ("Proximus",                                          84.91, ""),
    ("Crédit voiture",                                    724.12, ""),
    ("Frais bancaires trimestriels",                      11.25, ""),
    ("Intérêt crédit",                                    0.51, "Intérêts nets au 01-07"),
    ("Carburant",                                         60.86, "Q8 Easy Zaventem"),
    ("Assurance voiture",                                 458.66, "Domiciliation AG Insurance — prime passée de 431,25 à 458,66"),
    ("Paiement carte VISA",                               228.86, "Décompte n° 182"),
    ("Terrain de tennis - Orée ASBL",                     8.50, "À confirmer (terrain ou consommation)"),
    ("Carburant",                                         56.98, "Q8 Easy Zaventem"),
    ("Carburant",                                         62.27, "Q8 Easy Zaventem"),
    ("Parking",                                           1.60, "Woluwe-Saint-Lambert"),
    ("Péage autoroute France",                            34.40, "Domiciliation Autoroutes du Sud de la France"),
    ("Electrabel",                                        356.79, "Facture 455/1399/88731 — montant en hausse (256,99 les mois précédents)"),
    ("Telenet",                                           153.42, ""),
    ("Redevance de stationnement - Saint-Josse",          100.00, "Comm. 500/2300/37391 — à confirmer (redevance ou amende)"),
    ("Carburant",                                         60.90, "Maes Schaerbeek"),
    ("Parking",                                           1.60, "Woluwe-Saint-Lambert"),
    ("Repas Topogigio",                                   231.50, ""),
    ("Carburant",                                         43.01, "Esso Rumst"),
    ("Parking",                                           1.70, "Indigo, Tours (France)"),
    ("Parking",                                           2.80, "Commune de Soulac-sur-Mer (France)"),
 ],
}))

MOIS.append(("Août", {
 "solde_debut": 8568.89, "solde_fin": 2560.31, "extrait": "2025 - 008",
 "entrees": [
    ("Remboursement achat Decathlon - RTC Lambermont", 123.00, "Contrepartie de l'achat Decathlon du 14-08"),
 ],
 "depenses": [
    ("Précompte salarial juillet 2025 Thibault Duchène", 2250.00, ""),
    ("SD Worx",                                           331.79, ""),
    ("Entretien voiture - Garage Gobinau",                87.43, "Soulac-sur-Mer (France)"),
    ("Crédit voiture",                                    724.12, ""),
    ("Carburant",                                         72.01, "BP Esso Saint-Léger (France)"),
    ("Carburant",                                         77.28, "Shell Vémars (France)"),
    ("Achat matériel sportif - DECATHLON",                18.00, "Decathlon Evere"),
    ("Paiement carte VISA",                               2134.71, "Décompte n° 213"),
    ("Paiement carte MASTERCARD",                         66.74, "Décompte n° 216 - nouveau compte carte 80845055"),
    ("Parking",                                           1.60, "Woluwe-Saint-Lambert"),
    ("Achat matériel sportif - DECATHLON",                123.00, "Decathlon Evere - remboursé par le RTC Lambermont le même jour"),
    ("Carburant",                                         62.86, "Q8 Easy Zaventem"),
    ("Péage autoroute France",                            73.90, "Domiciliation Autoroutes du Sud de la France"),
    ("Carburant",                                         72.59, "Q8 Easy Zaventem"),
    ("Parking",                                           4.20, "Parking Parkpoort, Heverlee"),
    ("Parking",                                           3.00, "Parking Ladeuze, Louvain"),
    ("Parking",                                           2.80, "Indigo Park Docks, Bruxelles"),
    ("Parking",                                           5.00, "Parking Bokrijk, Genk"),
    ("Parking",                                           5.55, "Q-Park Woluwe Esplanade"),
    ("Parking",                                           12.00, "Brussels Expo — à confirmer (parking ou entrée)"),
    ("Parking",                                           3.00, "Parking Grand-Place, Bruxelles"),
 ],
}))
